### ISSUE TITLE
Additional Directions in Jupyter Notebook Tutorial on How to Exit

### ISSUE THREAD

**Issue by angelinechen** [biom262/biom262-2019#2]
Which extra credit option you plan on doing:
2. extending an existing explanation of a step

Description of what you will do:
Add directions to the Jupyter Notebook tutorial (~/biom262-2019/Module_1/Tutorials/How_to_load_jupyter_notebooks.ipynb) on how to exit the jupyter notebook when you ran the notebook in the background with '&'. 

Which files you will affect (if any): ~/biom262-2019/Module_1/Tutorials/How_to_load_jupyter_notebooks.ipynb

Which files you will create (if any): none

**Comment by danielanach** [comment]
Hi @angelinechen ,

This is a great idea. It is approved.

**Comment by danielanach** [comment]
Completed by @angelinechen in pull request #3 .
