### ISSUE TITLE
Tutorial on how to determine rRNA contamination

### ISSUE THREAD

**Issue by k7lee** [biom262/biom262-2019#4]
Which extra credit option you plan on doing:
4. submitting extra material or tutorials you put together yourself

Description of what you will do:
Create a tutorial on different ways to determine ribosomal RNA contamination of your library

Which files you will affect (if any): None

Which files you will create (if any): 
~/biom262-2019/Module_1/Tutorials/How_to_determine_rRNA_contamination.ipynb

**Comment by danielanach** [comment]
Good idea @k7lee !

Make sure you include rational on why you need to determine rRNA contamination.

Approved.

**Comment by danielanach** [comment]
Addressed by @k7lee in pull request #9 .
