### ISSUE TITLE
How to uses screens tutorial

### ISSUE THREAD

**Issue by nataliedef** [biom262/biom262-2019#5]
I plan on creating an tutorial on how to open and use screens, since this is something I find to be very useful and I don't believe there is any instructions in this github on how to use them. I will created a new file in Module 1 tutorials.

**Comment by danielanach** [comment]
Great! Screens are very useful and we could indeed use a tutorial on them.

Your extra credit is approved @nataliedef !

**Comment by danielanach** [comment]
Completed by @nataliedef in pull request #7 .
