### ISSUE TITLE
Tutorial: Using Galaxy for RNA-Seq

### ISSUE THREAD

**Issue by kcarolin** [biom262/biom262-2019#6]
Which extra credit option you plan on doing: (4) Submitting extra material or tutorials you put together yourself
Description of what you will do: I will walk through the use of Galaxy for RNA-Seq
Which files you will affect (if any): None
Which files you will create (if any): tutorial itself, in PDF format

**Comment by danielanach** [comment]
This sounds good @kcarolin ! If you have code,  it would be preferable for the format to by .ipynb, that way you can have cells for code. But otherwise pdf would be fine.

But otherwise this sounds good! Approved.

**Comment by danielanach** [comment]
Completed by @kcarolin in pull request #8 .
